name: verify

on:
  pull_request:
    branches: [ "main" ]
   
    types: [opened]

env:
  BASE_IMAGE: python:3.12-slim
  IMAGE_NAME: tiny-health-app
  CONTAINER_NAME: tiny-health-container
  APP_PORT: 8000

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run tests
        run: python -m unittest discover -s tests -v